name: wine-quality
dependencies:
  - numpy
  - pandas
  - jupyterlab
  - keras
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - sklearn
  - pip:
      - ann_visualizer
      - pydot
      - graphviz
      - h5py
      - python-pptx
  